apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ .Values.name }}"
spec:
  ports:
  - port: {{ .Values.redis_stack.redis_server_port }}
    name: "{{ .Values.name }}"
    targetPort: 2020

  type: NodePort
  selector:
    app: "{{ .Values.name }}"